/********************************************************************
* octDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error octDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableoctDict();
extern void G__cpp_setup_inheritanceoctDict();
extern void G__cpp_setup_typetableoctDict();
extern void G__cpp_setup_memvaroctDict();
extern void G__cpp_setup_globaloctDict();
extern void G__cpp_setup_memfuncoctDict();
extern void G__cpp_setup_funcoctDict();
extern void G__set_cpp_environmentoctDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "oct.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__octDictLN_TClass;
extern G__linked_taginfo G__octDictLN_TBuffer;
extern G__linked_taginfo G__octDictLN_TMemberInspector;
extern G__linked_taginfo G__octDictLN_Octet;

/* STUB derived class for protected member access */
