#include <TMultiGraph.h>
#include <TPad.h>
#include <TH2.h>
#include <TH1.h>
#include <TCut.h>
#include <TCanvas.h>
#include <TF1.h>
#include <TGraphErrors.h>
#include <TGraph.h>
#include <TTree.h>
#include <TBranch.h>
#include <TLeaf.h>
#include <TAxis.h>
#include <TChain.h>
#include <TStyle.h>
#include <TMath.h>
#include <TApplication.h>
#include <TString.h>
#include <TFile.h>
#include <TROOT.h>
#include <TSpectrum.h>
#include <TEllipse.h>

#include <iostream>
#include <cstdio>
#include <fstream>
