/********************************************************************
* RunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableRunDict();
extern void G__cpp_setup_inheritanceRunDict();
extern void G__cpp_setup_typetableRunDict();
extern void G__cpp_setup_memvarRunDict();
extern void G__cpp_setup_globalRunDict();
extern void G__cpp_setup_memfuncRunDict();
extern void G__cpp_setup_funcRunDict();
extern void G__set_cpp_environmentRunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/state/partition2/Data/2010analysis/includes/Run.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RunDictLN_TClass;
extern G__linked_taginfo G__RunDictLN_TBuffer;
extern G__linked_taginfo G__RunDictLN_TMemberInspector;
extern G__linked_taginfo G__RunDictLN_TObjArray;
extern G__linked_taginfo G__RunDictLN_TH1F;
extern G__linked_taginfo G__RunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__RunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__RunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__RunDictLN_TH2F;
extern G__linked_taginfo G__RunDictLN_TCanvas;
extern G__linked_taginfo G__RunDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__RunDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__RunDictLN_TTree;
extern G__linked_taginfo G__RunDictLN_TFile;
extern G__linked_taginfo G__RunDictLN_TRandom3;
extern G__linked_taginfo G__RunDictLN_Run;
extern G__linked_taginfo G__RunDictLN_RuncLcLbacks_t;

/* STUB derived class for protected member access */
