/********************************************************************
* BckRunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BckRunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBckRunDict();
extern void G__cpp_setup_inheritanceBckRunDict();
extern void G__cpp_setup_typetableBckRunDict();
extern void G__cpp_setup_memvarBckRunDict();
extern void G__cpp_setup_globalBckRunDict();
extern void G__cpp_setup_memfuncBckRunDict();
extern void G__cpp_setup_funcBckRunDict();
extern void G__set_cpp_environmentBckRunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/state/partition2/Data/2010analysis/includes/Bck_Run.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BckRunDictLN_TClass;
extern G__linked_taginfo G__BckRunDictLN_TBuffer;
extern G__linked_taginfo G__BckRunDictLN_TMemberInspector;
extern G__linked_taginfo G__BckRunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BckRunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__BckRunDictLN_Run;
extern G__linked_taginfo G__BckRunDictLN_Bck_Run;

/* STUB derived class for protected member access */
