/********************************************************************
* BetaRunDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BetaRunDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableBetaRunDict();
extern void G__cpp_setup_inheritanceBetaRunDict();
extern void G__cpp_setup_typetableBetaRunDict();
extern void G__cpp_setup_memvarBetaRunDict();
extern void G__cpp_setup_globalBetaRunDict();
extern void G__cpp_setup_memfuncBetaRunDict();
extern void G__cpp_setup_funcBetaRunDict();
extern void G__set_cpp_environmentBetaRunDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/state/partition2/Data/2010analysis/includes/Beta_Run.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BetaRunDictLN_TClass;
extern G__linked_taginfo G__BetaRunDictLN_TBuffer;
extern G__linked_taginfo G__BetaRunDictLN_TMemberInspector;
extern G__linked_taginfo G__BetaRunDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BetaRunDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__BetaRunDictLN_Run;
extern G__linked_taginfo G__BetaRunDictLN_Bck_Run;
extern G__linked_taginfo G__BetaRunDictLN_Beta_Run;

/* STUB derived class for protected member access */
