/********************************************************************
* OctetDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error OctetDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableOctetDict();
extern void G__cpp_setup_inheritanceOctetDict();
extern void G__cpp_setup_typetableOctetDict();
extern void G__cpp_setup_memvarOctetDict();
extern void G__cpp_setup_globalOctetDict();
extern void G__cpp_setup_memfuncOctetDict();
extern void G__cpp_setup_funcOctetDict();
extern void G__set_cpp_environmentOctetDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Octet.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OctetDictLN_TClass;
extern G__linked_taginfo G__OctetDictLN_TBuffer;
extern G__linked_taginfo G__OctetDictLN_TMemberInspector;
extern G__linked_taginfo G__OctetDictLN_TH1F;
extern G__linked_taginfo G__OctetDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__OctetDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__OctetDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__OctetDictLN_Beta_Run;
extern G__linked_taginfo G__OctetDictLN_Octet;

/* STUB derived class for protected member access */
